import { PalletteColorSet } from './color-palette.enum';

export const COLOR_PALETTE_MAIN_COLOR_ORDER: string[] = [
  'color1_base',
  'color2_base',
  'color3_base',
  'color4_base',
  'color5_base',
  'color6_base',
  'color7_base',
  'color8_base',
  'color9_base',

  'color1_dark',
  'color2_lighter',
  'color3_dark',
  'color4_lighter',
  'color5_dark',
  'color6_lighter',
  'color7_dark',
  'color8_lighter',
  'color9_dark',

  'color1_light',
  'color2_darker',
  'color3_light',
  'color4_darker',
  'color5_light',
  'color6_darker',
  'color7_light',
  'color8_darker',
  'color9_light',

  'color1_darker',
  'color2_light',
  'color3_darker',
  'color4_light',
  'color5_darker',
  'color6_light',
  'color7_darker',
  'color8_light',
  'color9_darker',

  'color1_lighter',
  'color2_dark',
  'color3_lighter',
  'color4_dark',
  'color5_lighter',
  'color6_dark',
  'color7_lighter',
  'color8_dark',
  'color9_lighter',
];

export const COLOR_PALETTE_SET1_COLOR_ORDER: string[] = [
  'color3_dark',
  'color6_darker',
  'color9_base',
  'color2_base',
  'color4_dark',
  'color5_base',
  'color3_light',
  'color6_base',
  'color9_lighter',
  'color2_dark',
  'color4_light',
  'color5_darker',
  'color3_lighter',
  'color6_dark',
  'color9_light',
  'color2_darker',
  'color4_lighter',
  'color5_dark',
  'color3_base',
  'color6_lighter',
  'color9_dark',
  'color2_lighter',
  'color4_darker',
  'color5_lighter',
  'color3_darker',
  'color6_light',
  'color9_darker',
  'color2_light',
  'color4_base',
  'color5_light',
];

export const COLOR_PALETTE_SET2_COLOR_ORDER: string[] = [
  'color2_base',
  'color9_base',
  'color1_base',
  'color6_dark',
  'color4_light',
  'color5_base',
  'color2_lighter',
  'color9_dark',
  'color1_dark',
  'color6_lighter',
  'color4_darker',
  'color5_dark',
  'color2_darker',
  'color9_light',
  'color1_light',
  'color6_base',
  'color4_base',
  'color5_light',
  'color2_light',
  'color9_darker',
  'color1_lighter',
  'color6_darker',
  'color4_lighter',
  'color5_darker',
  'color2_dark',
  'color9_lighter',
  'color1_darker',
  'color6_light',
  'color4_dark',
  'color5_lighter',
];

export const COLOR_PALETTE_SET3_COLOR_ORDER: string[] = [
  'color1_dark',
  'color2_light',
  'color4_base',
  'color9_base',
  'color6_dark',
  'color3_dark',
  'color1_base',
  'color2_lighter',
  'color4_lighter',
  'color9_dark',
  'color6_lighter',
  'color3_darker',
  'color1_light',
  'color2_darker',
  'color4_darker',
  'color9_light',
  'color6_darker',
  'color3_base',
  'color1_darker',
  'color2_base',
  'color4_light',
  'color9_darker',
  'color6_light',
  'color3_lighter',
  'color1_lighter',
  'color2_dark',
  'color4_dark',
  'color9_lighter',
  'color6_base',
  'color3_light',
];

export const COLOR_PALETTE_SET4_COLOR_ORDER: string[] = [
  'color6_dark',
  'color3_dark',
  'color2_light',
  'color5_base',
  'color9_light',
  'color7_darker',
  'color6_base',
  'color3_base',
  'color2_darker',
  'color5_dark',
  'color9_lighter',
  'color7_base',
  'color6_lighter',
  'color3_darker',
  'color2_base',
  'color5_darker',
  'color9_base',
  'color7_dark',
  'color6_light',
  'color3_lighter',
  'color2_dark',
  'color5_lighter',
  'color9_dark',
  'color7_light',
  'color6_darker',
  'color3_light',
  'color2_lighter',
  'color5_light',
  'color9_darker',
  'color7_lighter',
];

export const COLOR_PALETTE_SET5_COLOR_ORDER: string[] = [
  'color7_dark',
  'color9_base',
  'color3_base',
  'color4_base',
  'color5_base',
  'color6_darker',
  'color7_base',
  'color9_darker',
  'color3_light',
  'color4_darker',
  'color5_light',
  'color6_base',
  'color7_light',
  'color9_dark',
  'color3_lighter',
  'color4_dark',
  'color5_lighter',
  'color6_dark',
  'color7_lighter',
  'color9_light',
  'color3_dark',
  'color4_light',
  'color5_darker',
  'color6_light',
  'color7_darker',
  'color9_lighter',
  'color3_darker',
  'color4_lighter',
  'color5_dark',
  'color6_lighter',
];

export const COLOR_PALETTE_SET6_COLOR_ORDER: string[] = [
  'color5_base',
  'color7_darker',
  'color2_base',
  'color1_light',
  'color9_darker',
  'color8_dark',
  'color5_lighter',
  'color7_base',
  'color2_lighter',
  'color1_base',
  'color9_base',
  'color8_base',
  'color5_light',
  'color7_dark',
  'color2_light',
  'color1_dark',
  'color9_light',
  'color8_light',
  'color5_darker',
  'color7_lighter',
  'color2_darker',
  'color1_lighter',
  'color9_dark',
  'color8_darker',
  'color5_dark',
  'color7_light',
  'color2_dark',
  'color1_darker',
  'color9_lighter',
  'color8_lighter',
];

export const COLOR_PALETTE_SET7_COLOR_ORDER: string[] = [
  'color1_base',
  'color2_base',
  'color3_base',
  'color4_base',
  'color5_base',
  'color6_base',
  'color7_base',
  'color8_base',
  'color9_base',

  'color1_dark',
  'color2_dark',
  'color3_dark',
  'color4_dark',
  'color5_dark',
  'color6_dark',
  'color7_dark',
  'color8_dark',
  'color9_dark',

  'color1_darker',
  'color2_darker',
  'color3_darker',
  'color4_darker',
  'color5_darker',
  'color6_darker',
  'color7_darker',
  'color8_darker',
  'color9_darker',
];

// order of props here is important
export const COLOR_PALETTE_SETS_COLOR_ORDER: {
  [key in PalletteColorSet]?: string[];
} = {
  [PalletteColorSet.set1]: COLOR_PALETTE_SET1_COLOR_ORDER,
  [PalletteColorSet.set2]: COLOR_PALETTE_SET2_COLOR_ORDER,
  [PalletteColorSet.set3]: COLOR_PALETTE_SET3_COLOR_ORDER,
  [PalletteColorSet.set4]: COLOR_PALETTE_SET4_COLOR_ORDER,
  [PalletteColorSet.set5]: COLOR_PALETTE_SET5_COLOR_ORDER,
  [PalletteColorSet.set6]: COLOR_PALETTE_SET6_COLOR_ORDER,
  [PalletteColorSet.main]: COLOR_PALETTE_MAIN_COLOR_ORDER,
  [PalletteColorSet.set7]: COLOR_PALETTE_SET7_COLOR_ORDER,
};
