export enum RTEType {
  primary = 'primary',
  secondary = 'secondary',
  tertiary = 'tertiary',
}

export enum BlotType {
  size = 'fontSize',
  fontSize = 'fontSize',
  bold = 'bold',
  italic = 'italic',
  underline = 'underline',
  link = 'insertLink',
  insertLink = 'insertLink',
  list = 'list',
  ul = 'formatUL',
  ol = 'formatOL',
  formatUL = 'formatUL',
  formatOL = 'formatOL',
  align = 'align',
  direction = 'direction',
  rightToLeft = 'rightToLeft',
  leftToRight = 'leftToRight',
  placeholder = 'placeholder',
  mentions = 'mentions',
  emoticons = 'emoticons',
  video = 'insertVideo',
  insertVideo = 'insertVideo',
  image = 'insertImage',
  insertImage = 'insertImage',
}
