export enum IconSize {
  small = 'small',
  medium = 'medium',
  large = 'large',
}

export enum IconColor {
  dark = 'dark',
  normal = 'normal',
  light = 'light',
  white = 'white',
  primary = 'primary',
}

export enum Icons {
  home = 'sidebar_menu_home',
  people = 'sidebar_menu_people_',
  surveys = 'sidebar_menu_surveys',
  tasks = 'sidebar_menu_tasks',
  benefits = 'sidebar_menu_benefits',
  reports = 'sidebar_menu_reports',
  analytics = 'sidebar_menu_analytics',
  harmonise = 'sidebar_menu_harmonise',
  sidebar_settings = 'sidebar_menu_settings',
  calendar = 'calendar',
  toDos_link = 'todos_link',
  docs_link = 'docs_link',
  timeOff_link = 'time_off_icon',
  benefits_link = 'benefits_link',
  attendance_link = 'attendance_link',
  performance_link = 'performance_review_link',
  timeline_link = 'timeline_link',
  phone_link = 'phone_link',
  skype_link = 'skype_link',
  slack_link = 'slack_link',
  back_arrow_link = 'back_Icon',
  close = 'x',
  reset_x = 'reset_x',
  three_dots = 'three_dots',
  search = 'search_card_17px',
  reset = 'reset',
  bold = 'bold',
  italic = 'italic',
  underline = 'underline',
  link = 'link',
  text_size = 'text_size_option',
  question_mark = 'question_mark',
  department_icon = 'department_icon',
  company_icon = 'company_icon',
  edit_field_pencil = 'edit_field_pencil',
  folder = 'folder',
  add_doc = 'add_doc',
}
