export enum IconSize {
  small = 'small',
  medium = 'medium',
  large = 'large',
  xLarge = 'x-large'
}

export enum IconColor {
  dark = 'dark',
  normal = 'normal',
  light = 'light',
  white = 'white',
  primary = 'primary',
  inform = 'inform',
  negative = 'negative',
  positive = 'positive'
}

export enum Icons {
  home = 'sidebar_menu_home',
  people = 'sidebar_menu_people_',
  surveys = 'sidebar_menu_surveys',
  reports = 'sidebar_menu_reports',
  analytics = 'sidebar_menu_analytics',
  harmonise = 'sidebar_menu_harmonise',
  sidebar_settings = 'sidebar_menu_settings',
  calendar = 'calendar',
  toDos_link = 'todos_link',
  docs_link = 'docs_link',
  timeOff_link = 'time_off_icon',
  benefits_link = 'benefits_link',
  attendance_link = 'attendance_link',
  performance_link = 'performance_review_link',
  timeline_link = 'timeline_link',
  phone_link = 'phone_link',
  skype_link = 'skype_link',
  slack_link = 'slack_link',
  back_arrow_link = 'back_Icon',
  close = 'x',
  reset_x = 'reset_x',
  three_dots = 'three_dots',
  three_dots_vert = '3_dots_vert',
  search = 'search_card_17px',
  reset = 'baseline-settings_backup_restore-24px',
  bold = 'bold',
  italic = 'italic',
  underline = 'underline',
  link = 'link',
  text_size = 'text_size_option',
  question_mark = 'question_mark',
  department_icon = 'department_icon',
  company_icon = 'company_icon',
  edit_field_pencil = 'edit_field_pencil',
  folder = 'folder',
  add_doc = 'add_doc',
  timeline = 'Icon_timeline',
  employee_ref = 'employee_ref',
  docs_empty = 'docs_empty',
  baseline_info_icon = 'baseline_info_icon',
  doc_icon = 'doc_icon',
  arrow_forward = 'arrow_forward',
  error = 'error_icon',
  success = 'success_icon',
  warning = 'warning_icon',
  no_folder = 'no_folder',
  add_photo = 'add_photo',
  view_icon = 'view_icon',
  facebook = 'Facebook',
  linkedin = 'Linkedin',
  twitter = 'Twitter',

  // duplicate icons for backwards compatibility
  // TODO: remove if not used
  approve_badge = 'success_icon',
  pending_badge = 'Icon_timeline'
}
