export * from './typography.module';
export * from './big-body/big-body.component';
export * from './caption/caption.component';
export * from './display-1/display-1.component';
export * from './display-2/display-2.component';
export * from './display-3/display-3.component';
export * from './display-4/display-4.component';
export * from './heading/heading.component';
export * from './subheading/subheading.component';
