export enum Keys {
  alt = 'Alt',
  control = 'Control',
  shift = 'Shift',
  enter = 'Enter',
  escape = 'Escape',
  tab = 'Tab',
  arrowdown = 'ArrowDown',
  arrowleft = 'ArrowLeft',
  arrowright = 'ArrowRight',
  arrowup = 'ArrowUp',
  end = 'End',
  home = 'Home',
  pagedown = 'PageDown',
  pageup = 'PageUp',
  backspace = 'Backspace',
  delete = 'Delete',
  space = ' ',
  comma = ',',
  dollar = '$',
  at = '@'
}

export enum NativeEvents {
  click = 'click',
  dblclick = 'dblclick',
  mousedown = 'mousedown',
  mouseup = 'mouseup',
  mouseover = 'mouseover',
  mousemove = 'mousemove',
  mouseenter = 'mouseenter',
  mouseleave = 'mouseleave',
  mouseout = 'mouseout',
  dragstart = 'dragstart',
  drag = 'drag',
  dragenter = 'dragenter',
  dragleave = 'dragleave',
  dragover = 'dragover',
  drop = 'drop',
  dragend = 'dragend',
  keydown = 'keydown',
  keypress = 'keypress',
  keyup = 'keyup',
  resize = 'resize',
  scroll = 'scroll',
  select = 'select',
  change = 'change',
  submit = 'submit',
  reset = 'reset',
  focus = 'focus',
  blur = 'blur',
  touchstart = 'touchstart',
  touchend = 'touchend',
  touchmove = 'touchmove',
  touchenter = 'touchenter',
  touchleave = 'touchleave',
  touchcancel = 'touchcancel'
}
