export enum Keys {
  alt = 'Alt',
  control = 'Control',
  shift = 'Shift',
  enter = 'Enter',
  tab = 'Tab',
  arrowdown = 'ArrowDown',
  arrowleft = 'ArrowLeft',
  arrowright = 'ArrowRight',
  arrowup = 'ArrowUp',
  end = 'End',
  home = 'Home',
  pagedown = 'PageDown',
  pageup = 'PageUp',
  backspace = 'Backspace',
  delete = 'Delete',
  space = ' ',
  comma = ',',
  dollar = '$',
  at = '@'
}
