import { BlotType, UtilBlotType } from './rte.enum';
import { Blot } from 'parchment/dist/src/blot/abstract/blot';
import { DeltaStatic, RangeStatic } from 'quill';

export interface UpdateRteConfig {
  replaceStr: string;
  startIndex: number;
  insertText: string;
  format: UpdateRteConfigFormat;
  unformat?: string[];
  addSpaces?: boolean;
  noLinebreakAfter?: BlotType[];
}

type RteBlotFormat = { [key in BlotType | UtilBlotType]?: any };

interface UpdateRteConfigFormat {
  type: BlotType;
  value: any;
}

export interface RteLink {
  text: string;
  url: string;
}

export interface RteCurrentContent {
  body: string;
  plainText?: string;
}

export interface BlotData {
  index: number;
  endIndex: number;
  offset?: number;
  length: number;
  text: string;
  format?: RteBlotFormat;
  node?: Node | HTMLElement;
  blot?: Blot;
  element?: HTMLElement;
  link?: string;
  formatIs?: (f: string) => boolean;
  select?: () => RangeStatic;
  delete?: () => DeltaStatic;
}

export interface SpecialBlots {
  treatAsWhole?: BlotType[];
  treatAsWholeDefs: BlotType[];
  deleteAsWhole?: BlotType[];
  deleteAsWholeDefs: BlotType[];
  noLinebreakAfter?: BlotType[];
  noLinebreakAfterDefs: BlotType[];
}

export interface StoreCurrentResult {
  selection?: RangeStatic | boolean;
  currentBlot?: Partial<BlotData> | boolean;
  text?: string | boolean;
}

export interface FroalaOptions {
  apiKey?: string;
  app?: 'froala';
  attribution;
  autoStart;
  autofocus;
  aviaryKey;
  aviaryOptions;
  charCounterCount;
  charCounterMax;
  codeBeautifierOptions;
  codeMirror;
  codeMirrorOptions;
  codeViewKeepActiveButtons;
  codoxOptions;
  colorsBackground;
  colorsButtons;
  colorsHEXInput;
  colorsStep;
  colorsText;
  direction;
  disableRightClick;
  docId;
  documentReady;
  dragInline;
  editInPopup;
  editor;
  editorClass;
  embedlyEditButtons;
  embedlyInsertButtons;
  embedlyKey;
  embedlyScriptPath;
  emoticonsButtons;
  emoticonsSet;
  emoticonsStep;
  emoticonsUseImage;
  enter;
  entities;
  events;
  faButtons;
  fileAllowedTypes;
  fileInsertButtons;
  fileMaxSize;
  fileUpload;
  fileUploadMethod;
  fileUploadParam;
  fileUploadParams;
  fileUploadToS3;
  fileUploadURL;
  fileUseSelectedText;
  fontAwesomeSets;
  fontAwesomeTemplate;
  fontFamily;
  fontFamilyDefaultSelection;
  fontFamilySelection;
  fontSize;
  fontSizeDefaultSelection;
  fontSizeSelection;
  fontSizeUnit;
  formEditButtons;
  formMultipleStyles;
  formStyles;
  formUpdateButtons;
  fullPage;
  height;
  heightMax;
  heightMin;
  helpSets;
  htmlAllowComments;
  htmlAllowedAttrs;
  htmlAllowedEmptyTags;
  htmlAllowedStyleProps;
  htmlAllowedTags;
  htmlDoNotWrapTags;
  htmlExecuteScripts;
  htmlIgnoreCSSProperties;
  htmlRemoveTags;
  htmlSimpleAmpersand;
  htmlUntouched;
  iconsTemplate;
  iframe;
  iframeDefaultStyle;
  iframeStyle;
  iframeStyleFiles;
  imageAddNewLine;
  imageAllowedTypes;
  imageAltButtons;
  imageCORSProxy;
  imageDefaultAlign;
  imageDefaultDisplay;
  imageDefaultMargin;
  imageDefaultWidth;
  imageEditButtons;
  imageInsertButtons;
  imageManagerDeleteMethod;
  imageManagerDeleteParams;
  imageManagerDeleteURL;
  imageManagerLoadMethod;
  imageManagerLoadParams;
  imageManagerLoadURL;
  imageManagerPageSize;
  imageManagerPreloader;
  imageManagerScrollOffset;
  imageManagerToggleTags;
  imageMaxSize;
  imageMinWidth;
  imageMove;
  imageMultipleStyles;
  imageOutputSize;
  imagePaste;
  imagePasteProcess;
  imageResize;
  imageResizeWithPercent;
  imageRoundPercent;
  imageSizeButtons;
  imageSplitHTML;
  imageStyles;
  imageTUIOptions;
  imageTextNear;
  imageUpload;
  imageUploadMethod;
  imageUploadParam;
  imageUploadParams;
  imageUploadRemoteUrls;
  imageUploadToS3;
  imageUploadURL;
  indentMargin;
  initOnClick;
  inlineClasses;
  inlineStyles;
  keepFormatOnDelete;
  language;
  lineBreakerHorizontalOffset;
  lineBreakerOffset;
  lineBreakerTags;
  lineHeights;
  linkAlwaysBlank;
  linkAlwaysNoFollow;
  linkAttributes;
  linkAutoPrefix;
  linkConvertEmailAddress;
  linkEditButtons;
  linkInsertButtons;
  linkList;
  linkMultipleStyles;
  linkNoOpener;
  linkNoReferrer;
  linkStyles;
  linkText;
  listAdvancedTypes;
  multiLine;
  paragraphDefaultSelection;
  paragraphFormat;
  paragraphFormatSelection;
  paragraphMultipleStyles;
  paragraphStyles;
  pasteAllowLocalImages;
  pasteAllowedStyleProps;
  pasteDeniedAttrs;
  pasteDeniedTags;
  pastePlain;
  placeholderText;
  pluginsEnabled;
  quickInsertButtons;
  quickInsertEnabled;
  quickInsertTags;
  requestHeaders;
  requestWithCORS;
  requestWithCredentials;
  saveInterval;
  saveMethod;
  saveParam;
  saveParams;
  saveURL;
  scrollableContainer;
  shortcutsEnabled;
  shortcutsHint;
  specialCharButtons;
  specialCharactersSets;
  spellcheck;
  tabIndex;
  tabSpaces;
  tableCellMultipleStyles;
  tableCellStyles;
  tableColors;
  tableColorsButtons;
  tableColorsStep;
  tableDefaultWidth;
  tableEditButtons;
  tableInsertButtons;
  tableInsertHelper;
  tableInsertHelperOffset;
  tableInsertMaxSize;
  tableMultipleStyles;
  tableResizer;
  tableResizerOffset;
  tableResizingLimit;
  tableStyles;
  theme;
  toolbarBottom;
  toolbarButtons;
  toolbarButtonsMD;
  toolbarButtonsSM;
  toolbarButtonsXS;
  toolbarContainer;
  toolbarInline;
  toolbarSticky;
  toolbarStickyOffset;
  toolbarVisibleWithoutSelection;
  tooltips;
  typingTimer;
  useClasses;
  username;
  videoAllowedProviders;
  videoAllowedTypes;
  videoDefaultAlign;
  videoDefaultDisplay;
  videoDefaultWidth;
  videoEditButtons;
  videoInsertButtons;
  videoMaxSize;
  videoMove;
  videoResize;
  videoResponsive;
  videoSizeButtons;
  videoSplitHTML;
  videoTextNear;
  videoUpload;
  videoUploadMethod;
  videoUploadParam;
  videoUploadParams;
  videoUploadToS3;
  videoUploadURL;
  width;
  wordAllowedStyleProps;
  wordDeniedAttrs;
  wordDeniedTags;
  wordPasteKeepFormatting;
  wordPasteModal;
  zIndex;
}
